apiVersion: v1
kind: Service
metadata:
  labels:
    app: capsule
  name: capsule
  namespace: capsule-system
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    name: capsule
  type: ClusterIP
